services:
  api:
    build:
      context: .
      dockerfile: dockerfile
      
    container_name: node-api

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production

    volumes:
      - .:/app
      - /app/node-modules

    command: npm run dev        